package Sample;
import java.util.ArrayList;
import java.io.FileReader;

public class TryCatchFinally {
	public static void main(String[] args) {
		
		try {
			// NullPointerExceptionが発生
			String str = "value:".concat(null);
			
			// ArrayIndexOutOfBoundsExceptionが発生
			int[] array = {1,2,3,4,5};
			System.out.println(array[5]);
			
			// IndexOutOdBoundsExceptionが発生
			ArrayList<String> list = new ArrayList<>();
			list.add("Hi!");
			list.add("Hello");
			list.add("Hi,dear!");
			list.get(3);
			
			// IOException発生をcatchしていないのでコンパイルエラー
//			FileReader reader = new FileReader("not_exist_file.txt");

//            int c;
//            while ((c = reader.read()) != -1) {
//                System.out.print((char) c);
//            }
//            reader.close();
		
		// catchする例外はORで書ける
		} catch (IndexOutOfBoundsException | NullPointerException e) {
			System.out.println("Catch IndexOutOfBoundsException!");
			
		// IndexOutOfBoundsException(親クラス)を上でcatchしているのでコンパイルエラー
//		} catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("ArrayIndexOutOfBoundsException!");
			
		} catch (RuntimeException e) {
			System.out.println("Catch RuntimeException!");
			
		} finally {
			System.out.println("This is finally");
		} 
	}
}
